PivotX\CoreBundle\Entity\LocalEmbedResource:
  type: entity
  table: null
  fields:
    publicid:
      type: string
      length: 64
      precision: 0
      scale: 0
      nullable: true
      unique: true
      auto_entity:
        pivotx_ignore:
          ~
    fileid:
      type: string
      length: 40
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        pivotx_ignore:
          ~
    filename:
      type: string
      length: 100
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        pivotx_backendfile:
          ~
    filesize:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        pivotx_ignore:
          ~
