PivotX\CoreBundle\Entity\RemoteEmbedResource:
  type: entity
  table: null
  fields:
    uri:
      type: string
      length: 250
      precision: 0
      scale: 0
      nullable: false
      unique: false
    responses:
      type: text
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
