PivotX\CoreBundle\Entity\User:
  type: entity
  table: user
  repositoryClass: PivotX\CoreBundle\Model\UserRepository
  fields:
    id:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      id: true
      generator:
        strategy: IDENTITY
    date_created:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: create
    date_modified:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: update
    date_last_login:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: true
      unique: false
      auto_entity:
        pivotx_ignore:
          ~
    enabled:
      type: boolean
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    level:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        pivotx_type:
          type:     'choice'
          choices:
            100:    'Site access (no PivotX access)'
            200:    'Editorial access'
            500:    'Administrative access'
            800:    'Developer access'
            900:    'Superadmin access'
    email:
      type: string
      length: 250
      precision: 0
      scale: 0
      nullable: true
      unique: true
    passwd_salt:
      type: string
      length: 128
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        passwordable:
          type: salt
    passwd:
      type: string
      length: 128
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        passwordable:
          type: password
    theme_name:
      type: string
      length: 64
      precision: 0
      scale: 0
      nullable: true
      unique: false
  oneToMany:
    activitylogs:
      targetEntity: User
      mappedBy: user
      fetch: EXTRA_LAZY
  auto_entity:
    loggable:
      limits:
        days:        365
        records:     100
      remove-fields: [ 'passwd', 'passwd_salt' ]
